import jsPDF from 'jspdf'

interface ORFData {
  id: string
  frame: string
  start: number
  end: number
  length_nt: number
  length_aa: number
  protein_sequence: string
  gc_content: number
  molecular_weight: number
  isoelectric_point: number
  start_codon: string
  stop_codon: string
}

interface RestrictionSite {
  id: string
  enzyme: string
  recognition_sequence: string
  cut_position: number
  start_position: number
  end_position: number
  end_type: 'sticky' | 'blunt'
  overhang: string
}

interface Fragment {
  id: string
  start: number
  end: number
  length: number
  sequence: string
}

interface GuideRNAData {
  id: string
  sequence: string
  pam_sequence: string
  strand: '+' | '-'
  position: number
  gc_content: number
  cleavage_position: number
  efficiency_score: number
  off_target_risk: 'low' | 'medium' | 'high'
}

interface PAMSiteData {
  id: string
  sequence: string
  position: number
  strand: '+' | '-'
}

export function generateORFReport(data: {
  sequence: string
  sequence_length: number
  total_orfs: number
  longest_orf: ORFData | null
  average_length: number
  most_active_frame: string
  orfs: ORFData[]
  timestamp: string
}) {
  const doc = new jsPDF()
  let yPosition = 20

  // Header
  doc.setFontSize(20)
  doc.setTextColor(0, 207, 255)
  doc.text('HelixLab - ORF Detection Report', 20, yPosition)
  yPosition += 15

  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated on: ${data.timestamp}`, 20, yPosition)
  yPosition += 20

  // Summary Section
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text('Analysis Summary', 20, yPosition)
  yPosition += 10

  doc.setFontSize(10)
  const summaryData = [
    `Sequence Length: ${data.sequence_length.toLocaleString()} bp`,
    `Total ORFs Found: ${data.total_orfs}`,
    `Longest ORF: ${data.longest_orf?.length_nt || 0} bp (Frame ${data.longest_orf?.frame || 'N/A'})`,
    `Average ORF Length: ${data.average_length} bp`,
    `Most Active Frame: ${data.most_active_frame}`
  ]

  summaryData.forEach(line => {
    doc.text(line, 20, yPosition)
    yPosition += 6
  })

  yPosition += 10

  // ORF Details Table
  if (data.orfs.length > 0) {
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text('ORF Details', 20, yPosition)
    yPosition += 10

    // Table headers
    doc.setFontSize(8)
    doc.setTextColor(0, 0, 0)
    const headers = ['Frame', 'Start', 'End', 'Length (bp)', 'Length (aa)', 'GC%', 'MW (kDa)']
    let xPos = 20
    headers.forEach((header, index) => {
      doc.text(header, xPos, yPosition)
      xPos += 25
    })
    yPosition += 8

    // Table data
    data.orfs.slice(0, 30).forEach(orf => { // Limit to first 30 ORFs to fit on page
      if (yPosition > 270) { // Start new page if needed
        doc.addPage()
        yPosition = 20
      }

      xPos = 20
      const rowData = [
        orf.frame,
        orf.start.toString(),
        orf.end.toString(),
        orf.length_nt.toString(),
        orf.length_aa.toString(),
        `${orf.gc_content}%`,
        `${orf.molecular_weight}`
      ]

      rowData.forEach(data => {
        doc.text(data, xPos, yPosition)
        xPos += 25
      })
      yPosition += 6
    })

    if (data.orfs.length > 30) {
      yPosition += 5
      doc.setFontSize(8)
      doc.setTextColor(100, 100, 100)
      doc.text(`... and ${data.orfs.length - 30} more ORFs`, 20, yPosition)
    }
  }

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(100, 100, 100)
  doc.text('Generated by HelixLab - Professional DNA Analysis Platform', 20, 285)

  // Save the PDF
  doc.save(`HelixLab_ORF_Report_${new Date().toISOString().split('T')[0]}.pdf`)
}

export function generateRestrictionReport(data: {
  sequence: string
  sequence_length: number
  restriction_sites: RestrictionSite[]
  fragments: Fragment[]
  total_sites: number
  total_fragments: number
  largest_fragment: Fragment | null
  smallest_fragment: Fragment | null
  most_active_enzyme: string
  timestamp: string
}) {
  const doc = new jsPDF()
  let yPosition = 20

  // Header
  doc.setFontSize(20)
  doc.setTextColor(0, 207, 255)
  doc.text('HelixLab - Restriction Mapping Report', 20, yPosition)
  yPosition += 15

  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated on: ${data.timestamp}`, 20, yPosition)
  yPosition += 20

  // Summary Section
  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text('Analysis Summary', 20, yPosition)
  yPosition += 10

  doc.setFontSize(10)
  const summaryData = [
    `Sequence Length: ${data.sequence_length.toLocaleString()} bp`,
    `Total Restriction Sites: ${data.total_sites}`,
    `Total Fragments: ${data.total_fragments}`,
    `Largest Fragment: ${data.largest_fragment?.length || 0} bp`,
    `Smallest Fragment: ${data.smallest_fragment?.length || 0} bp`,
    `Most Active Enzyme: ${data.most_active_enzyme}`
  ]

  summaryData.forEach(line => {
    doc.text(line, 20, yPosition)
    yPosition += 6
  })

  yPosition += 10

  // Restriction Sites Table
  if (data.restriction_sites.length > 0) {
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text('Restriction Sites', 20, yPosition)
    yPosition += 10

    // Table headers
    doc.setFontSize(8)
    doc.setTextColor(0, 0, 0)
    const headers = ['Enzyme', 'Recognition', 'Cut Position', 'End Type', 'Overhang']
    let xPos = 20
    headers.forEach((header, index) => {
      doc.text(header, xPos, yPosition)
      xPos += 35
    })
    yPosition += 8

    // Table data
    data.restriction_sites.slice(0, 25).forEach(site => { // Limit to first 25 sites
      if (yPosition > 270) { // Start new page if needed
        doc.addPage()
        yPosition = 20
      }

      xPos = 20
      const rowData = [
        site.enzyme,
        site.recognition_sequence,
        site.cut_position.toString(),
        site.end_type,
        site.overhang
      ]

      rowData.forEach(data => {
        doc.text(data, xPos, yPosition)
        xPos += 35
      })
      yPosition += 6
    })

    if (data.restriction_sites.length > 25) {
      yPosition += 5
      doc.setFontSize(8)
      doc.setTextColor(100, 100, 100)
      doc.text(`... and ${data.restriction_sites.length - 25} more sites`, 20, yPosition)
    }
  }

  // Fragments Section
  if (data.fragments.length > 0 && yPosition < 200) {
    yPosition += 15
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text('Fragment Analysis', 20, yPosition)
    yPosition += 10

    doc.setFontSize(8)
    const fragHeaders = ['Fragment', 'Start', 'End', 'Length (bp)']
    let xPos = 20
    fragHeaders.forEach(header => {
      doc.text(header, xPos, yPosition)
      xPos += 40
    })
    yPosition += 8

    data.fragments.slice(0, 15).forEach((fragment, index) => {
      if (yPosition > 270) return // Skip if no space

      xPos = 20
      const fragData = [
        `Fragment ${index + 1}`,
        fragment.start.toString(),
        fragment.end.toString(),
        `${fragment.length} bp`
      ]

      fragData.forEach(data => {
        doc.text(data, xPos, yPosition)
        xPos += 40
      })
      yPosition += 6
    })
  }

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(100, 100, 100)
  doc.text('Generated by HelixLab - Professional DNA Analysis Platform', 20, 285)

  // Save the PDF
  doc.save(`HelixLab_Restriction_Report_${new Date().toISOString().split('T')[0]}.pdf`)
}

export function generateCRISPRReport(data: {
  sequence: string
  sequence_length: number
  total_guides: number
  best_guide: GuideRNAData | null
  lowest_off_target: GuideRNAData | null
  pam_sites: PAMSiteData[]
  guide_rnas: GuideRNAData[]
  timestamp: string
}) {
  const doc = new jsPDF()

  // Header
  doc.setFontSize(20)
  doc.setTextColor(0, 207, 255)
  doc.text('HelixLab CRISPR Guide Finder Report', 20, 30)

  // Subtitle
  doc.setFontSize(12)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated on ${data.timestamp}`, 20, 40)

  let yPosition = 55

  // Summary Section
  doc.setFontSize(16)
  doc.setTextColor(0, 0, 0)
  doc.text('Analysis Summary', 20, yPosition)
  yPosition += 15

  doc.setFontSize(10)
  doc.text(`Sequence Length: ${data.sequence_length.toLocaleString()} bp`, 20, yPosition)
  yPosition += 6
  doc.text(`Total Guide RNAs Found: ${data.total_guides}`, 20, yPosition)
  yPosition += 6
  doc.text(`Total PAM Sites: ${data.pam_sites.length}`, 20, yPosition)
  yPosition += 6
  doc.text(`Best Efficiency Score: ${data.best_guide?.efficiency_score || 0}%`, 20, yPosition)
  yPosition += 6
  doc.text(`Lowest Off-Target Risk: ${data.lowest_off_target?.off_target_risk || 'N/A'}`, 20, yPosition)
  yPosition += 15

  // Best Guide RNA Section
  if (data.best_guide) {
    doc.setFontSize(14)
    doc.setTextColor(0, 212, 170)
    doc.text('Recommended Guide RNA', 20, yPosition)
    yPosition += 10

    doc.setFontSize(10)
    doc.setTextColor(0, 0, 0)
    doc.text(`Guide ID: ${data.best_guide.id}`, 20, yPosition)
    yPosition += 6
    doc.text(`Sequence (5' → 3'): ${data.best_guide.sequence}`, 20, yPosition)
    yPosition += 6
    doc.text(`PAM Sequence: ${data.best_guide.pam_sequence}`, 20, yPosition)
    yPosition += 6
    doc.text(`Strand: ${data.best_guide.strand}`, 20, yPosition)
    yPosition += 6
    doc.text(`Position: ${data.best_guide.position}`, 20, yPosition)
    yPosition += 6
    doc.text(`Cleavage Position: ${data.best_guide.cleavage_position}`, 20, yPosition)
    yPosition += 6
    doc.text(`GC Content: ${data.best_guide.gc_content}%`, 20, yPosition)
    yPosition += 6
    doc.text(`Efficiency Score: ${data.best_guide.efficiency_score}%`, 20, yPosition)
    yPosition += 6
    doc.text(`Off-Target Risk: ${data.best_guide.off_target_risk}`, 20, yPosition)
    yPosition += 15
  }

  // All Guide RNAs Table
  if (data.guide_rnas.length > 0) {
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text('All Guide RNAs', 20, yPosition)
    yPosition += 10

    // Table headers
    doc.setFontSize(8)
    doc.setTextColor(0, 0, 0)
    const headers = ['Rank', 'Guide Sequence', 'PAM', 'Strand', 'Position', 'GC%', 'Efficiency', 'Risk']
    let xPos = 20
    const colWidths = [12, 45, 15, 15, 20, 12, 18, 15]
    headers.forEach((header, index) => {
      doc.text(header, xPos, yPosition)
      xPos += colWidths[index]
    })
    yPosition += 8

    // Table data
    data.guide_rnas.slice(0, 25).forEach((guide, index) => { // Limit to first 25 guides
      if (yPosition > 270) { // Start new page if needed
        doc.addPage()
        yPosition = 20
      }

      xPos = 20
      const rowData = [
        `${index + 1}`,
        guide.sequence.substring(0, 12) + (guide.sequence.length > 12 ? '...' : ''),
        guide.pam_sequence,
        guide.strand,
        guide.position.toString(),
        `${guide.gc_content}%`,
        `${guide.efficiency_score}%`,
        guide.off_target_risk
      ]

      rowData.forEach((data, colIndex) => {
        doc.text(data, xPos, yPosition)
        xPos += colWidths[colIndex]
      })
      yPosition += 6
    })

    if (data.guide_rnas.length > 25) {
      yPosition += 5
      doc.setFontSize(8)
      doc.setTextColor(100, 100, 100)
      doc.text(`... and ${data.guide_rnas.length - 25} more guide RNAs`, 20, yPosition)
    }
  }

  // PAM Sites Summary
  if (data.pam_sites.length > 0 && yPosition < 220) {
    yPosition += 15
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text('PAM Sites Distribution', 20, yPosition)
    yPosition += 10

    const forwardPAMs = data.pam_sites.filter(p => p.strand === '+').length
    const reversePAMs = data.pam_sites.filter(p => p.strand === '-').length

    doc.setFontSize(10)
    doc.text(`Forward Strand (+): ${forwardPAMs} PAM sites`, 20, yPosition)
    yPosition += 6
    doc.text(`Reverse Strand (-): ${reversePAMs} PAM sites`, 20, yPosition)
    yPosition += 6
    doc.text(`Total PAM Sites: ${data.pam_sites.length}`, 20, yPosition)
    yPosition += 15
  }

  // CRISPR Guidelines
  if (yPosition < 200) {
    doc.setFontSize(14)
    doc.setTextColor(0, 0, 0)
    doc.text('CRISPR-Cas9 Guidelines', 20, yPosition)
    yPosition += 10

    doc.setFontSize(9)
    const guidelines = [
      '• Target efficiency scores >70% for optimal cutting',
      '• Avoid guides with high off-target risk',
      '• Consider multiple guides for redundancy',
      '• Validate guides experimentally before use',
      '• Check for SNPs in target population',
      '• Design guides 3-4 bp from desired cut site'
    ]

    guidelines.forEach(guideline => {
      if (yPosition < 270) {
        doc.text(guideline, 20, yPosition)
        yPosition += 6
      }
    })
  }

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(100, 100, 100)
  doc.text('Generated by HelixLab - Professional DNA Analysis Platform', 20, 285)

  // Save the PDF
  doc.save(`HelixLab_CRISPR_Report_${new Date().toISOString().split('T')[0]}.pdf`)
}
export function generateCodonReport(data: {
  originalSequence: string
  optimizedSequence: string
  proteinSequence: string
  organism: string
  originalGC: number
  optimizedGC: number
  caiOriginal: number
  caiOptimized: number
  rareCodonCount: number
  optimizedCodonCount: number
  totalCodons: number
  proteinPreserved: boolean
  analysisTime: number
  timestamp: string
}) {
  const doc = new jsPDF()
  let y = 20

  doc.setFontSize(20)
  doc.setTextColor(0, 207, 255)
  doc.text('HelixLab - Codon Optimization Report', 20, y); y += 12

  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text(`Generated: ${data.timestamp}`, 20, y); y += 18

  doc.setFontSize(14)
  doc.setTextColor(0, 0, 0)
  doc.text('Analysis Summary', 20, y); y += 10

  doc.setFontSize(10)
  const orgNames: Record<string,string> = { ecoli:'E. coli', human:'Human', yeast:'Yeast', bacillus:'Bacillus subtilis', mouse:'Mouse' }
  const summary = [
    `Target Organism: ${orgNames[data.organism] || data.organism}`,
    `Sequence Length: ${data.originalSequence.length} bp`,
    `Total Codons: ${data.totalCodons}`,
    `Rare Codons Found: ${data.rareCodonCount}`,
    `Codons Optimized: ${data.optimizedCodonCount}`,
    `Original GC Content: ${data.originalGC}%`,
    `Optimized GC Content: ${data.optimizedGC}%`,
    `Original CAI: ${data.caiOriginal}`,
    `Optimized CAI: ${data.caiOptimized}`,
    `Protein Preserved: ${data.proteinPreserved ? 'Yes' : 'No - MISMATCH DETECTED'}`,
    `Analysis Time: ${data.analysisTime}ms`,
  ]
  summary.forEach(line => { doc.text(line, 20, y); y += 6 })
  y += 8

  doc.setFontSize(14)
  doc.setTextColor(0, 212, 170)
  doc.text('Protein Sequence', 20, y); y += 10
  doc.setFontSize(8)
  doc.setTextColor(0, 0, 0)
  const proteinLines = doc.splitTextToSize(data.proteinSequence, 170)
  proteinLines.forEach((line: string) => {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.text(line, 20, y); y += 5
  })
  y += 8

  doc.setFontSize(14)
  doc.setTextColor(0, 207, 255)
  doc.text('Original DNA Sequence', 20, y); y += 10
  doc.setFontSize(7)
  doc.setTextColor(0, 0, 0)
  const origLines = doc.splitTextToSize(data.originalSequence, 170)
  origLines.slice(0, 30).forEach((line: string) => {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.text(line, 20, y); y += 4
  })
  if (origLines.length > 30) { doc.text(`... (${data.originalSequence.length - origLines.slice(0,30).join('').length} more bp)`, 20, y); y += 4 }
  y += 8

  doc.setFontSize(14)
  doc.setTextColor(0, 212, 170)
  doc.text('Optimized DNA Sequence', 20, y); y += 10
  doc.setFontSize(7)
  doc.setTextColor(0, 0, 0)
  const optLines = doc.splitTextToSize(data.optimizedSequence, 170)
  optLines.slice(0, 30).forEach((line: string) => {
    if (y > 270) { doc.addPage(); y = 20 }
    doc.text(line, 20, y); y += 4
  })
  if (optLines.length > 30) { doc.text(`... (${data.optimizedSequence.length - optLines.slice(0,30).join('').length} more bp)`, 20, y); y += 4 }

  doc.setFontSize(8)
  doc.setTextColor(100, 100, 100)
  doc.text('Generated by HelixLab - Professional DNA Analysis Platform', 20, 285)
  doc.save(`HelixLab_Codon_Report_${new Date().toISOString().split('T')[0]}.pdf`)
}
